# Setup FastAPI app. Configs are read from GCP SM through ESO SecretStore.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  labels:
    app: backend-api
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: eu.gcr.io/quiz-craft-398712/quiz-craft-api
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-admin-admin
              key: connectionString.standardSrv
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: fastapi-secrets
              key: jwt_secret_key
        - name: MAIL_SERVER_USER
          valueFrom:
            secretKeyRef:
              name: fastapi-secrets
              key: mail_server_user
        - name: MAIL_SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fastapi-secrets
              key: mail_server_password
        volumeMounts:
        - name: decouple-config
          mountPath: "/config/fastapi"
          readOnly: true
      volumes:
      - name: decouple-config
        configMap:
          name: fastapi-configmap
          items:
          - key: "decouple.config"
            path: ".env"
