# Setup SecretStore from GCP Secret Manager. Needs Workload Identity Provider mechanism set up to authenticate with GCP. For more info consult ESO docs on gcpsm provider.
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-store
  namespace: default
spec:
  provider:
    gcpsm:
      projectID: quiz-craft-398712
---
# Setup external secrets from SecretStore. ESO will turn these into K8s secrets automatically.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: gcp-store
  target:
    name: database-admin-password
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: mongodb-admin-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fastapi-external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: gcp-store
  target:
    name: fastapi-secrets
    creationPolicy: Owner
  data:
  - secretKey: jwt_secret_key
    remoteRef:
      key: jwt-secret-key
  - secretKey: mail_server_user
    remoteRef:
      key: mail-server-user
  - secretKey: mail_server_password
    remoteRef:
      key: mail-server-password
