name: Build and Deploy React

on:
  push:
    branches:
      - main
    paths:
      - client
  workflow_dispatch:


env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  DEPLOYMENT_NAME: frontend-react-prod
  REACT_IMAGE_NAME: quiz-craft-react
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

jobs:
  build-publish-react:
    name: Setup, Build, and Publish React Image
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write # This is required for requesting the JWT
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: "gcloud-auth"
        name: "Authenticate to GCP"
        uses: "google-github-actions/auth@v1.1.1"
        with:
          create_credentials_file: "true"
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER}}
          service_account: ${{ env.GOOGLE_SERVICE_ACCOUNT }}
      - id: "gcloud"
        name: "gcloud"
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.gcloud-auth.outputs.credentials_file_path }}"
      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - name: Setup Docker to use gcloud container registry
        run: |-
          gcloud --quiet auth configure-docker

      # Build React Docker image
      - name: Build React Image
        run: |-
          docker build \
            --tag "eu.gcr.io/$PROJECT_ID/$REACT_IMAGE_NAME:$GITHUB_SHA" \
            --tag "eu.gcr.io/$PROJECT_ID/$REACT_IMAGE_NAME:latest" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            ./client/quiz-craft

      # Push React Docker image to Google Container Registry
      - name: Publish React Image
        run: |-
          docker push "eu.gcr.io/$PROJECT_ID/$REACT_IMAGE_NAME:$GITHUB_SHA"
          docker push "eu.gcr.io/$PROJECT_ID/$REACT_IMAGE_NAME:latest"
  deploy-react:
    name: Deploy React Image to GKE
    needs: [build-publish-react]
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write # This is required for requesting the JWT
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: "gcloud-auth"
        name: "Authenticate to GCP"
        uses: "google-github-actions/auth@v1.1.1"
        with:
          create_credentials_file: "true"
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER}}
          service_account: ${{ env.GOOGLE_SERVICE_ACCOUNT }}
      - id: "gcloud"
        name: "gcloud"
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.gcloud-auth.outputs.credentials_file_path }}"

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      # Deploy the Docker image to the GKE cluster
      - name: Deploy React Image
        run: |-
          kubectl apply -f K8s/secrets.yaml
          kubectl apply -f K8s/configMaps.yaml
          kubectl set image deployments/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=eu.gcr.io/$PROJECT_ID/$REACT_IMAGE_NAME:$GITHUB_SHA
          kubectl rollout status deployment/$DEPLOYMENT_NAME
