name: Deploy React Image to GKE

on:
 workflow_run:
    workflows: ["Build and Publish React Image"]
    types:
      - completed

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  DEPLOYMENT_NAME: frontend-react-prod
  REACT_IMAGE_NAME: quiz-craft-react
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

jobs:
  setup-deploy-react:
    name: Setup and Deploy React Image
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write # This is required for requesting the JWT
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: "gcloud-auth"
        name: "Authenticate to GCP"
        uses: "google-github-actions/auth@v1.1.1"
        with:
          create_credentials_file: "true"
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER}}
          service_account: ${{ env.GOOGLE_SERVICE_ACCOUNT }}
      - id: "gcloud"
        name: "gcloud"
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.gcloud-auth.outputs.credentials_file_path }}"

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      # Deploy the Docker image to the GKE cluster
      - name: Deploy React Image
        run: |-
          kubectl apply -f K8s/secrets.yaml
          kubectl apply -f K8s/configMaps.yaml
          kubectl set image deployments/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=eu.gcr.io/$PROJECT_ID/$REACT_IMAGE_NAME:$GITHUB_SHA
          kubectl rollout status deployment/$DEPLOYMENT_NAME
