name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  DEPLOYMENT_NAME: ${{ secrets.GKE_DEPLOYMENT_NAME }}
  API_IMAGE_NAME: quiz-craft-api
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write # This is required for requesting the JWT
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: 'gcloud-auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v1.1.1'
      with:
          create_credentials_file: 'true'
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER}}
          service_account: ${{ env.GOOGLE_SERVICE_ACCOUNT }}
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.gcloud-auth.outputs.credentials_file_path }}"
  # Configure Docker to use the gcloud command-line tool as a credential
  # helper for authentication
    - name: Setup Docker to use gcloud container registry
      run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # Build the Docker image
    - name: Build API Image
      run: |-
        docker build \
          --tag "eu.gcr.io/$PROJECT_ID/$API_IMAGE_NAME:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          ./FastAPI

    # Push the Docker image to Google Container Registry
    - name: Publish API Image
      run: |-
        docker push "eu.gcr.io/$PROJECT_ID/$API_IMAGE_NAME:$GITHUB_SHA"

    # Deploy the Docker image to the GKE cluster
    - name: Deploy API Image
      run: |-
        kubectl apply -f K8s/secrets.yaml
        kubectl apply -f K8s/configMaps.yaml
        kubectl apply -f K8s/main.yaml
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide
